version: '3'

services:
  tabular-neo4j:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    env_file:
      - .env
    network_mode: "host"

networks:
  tabular-neo4j-network:
    driver: bridge
