version: '3'

services:
  tabular-neo4j:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    environment:
      - LMSTUDIO_HOST=127.0.0.1
      - LMSTUDIO_PORT=1234
    network_mode: "host"

networks:
  tabular-neo4j-network:
    driver: bridge
