version: '3'

services:
  tabular-neo4j:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
      - ./neo4j/import:/import
    env_file:
      - .env
    depends_on:
      neo4j:
        condition: service_healthy
    network_mode: "host"
# Note: Using host networking so the app can reach local LLMs (Ollama/LMStudio on localhost)
# Neo4j is still available via bolt://localhost:7687 from the app

  neo4j:
    image: neo4j:5.18-community
    environment:
      - NEO4J_AUTH=neo4j/password
      - NEO4J_PLUGINS=["apoc"]
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
      - NEO4J_dbms_connector_bolt_advertised__address=neo4j:7687
      - NEO4J_dbms_connector_http_advertised__address=neo4j:7474
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - ./neo4j/data:/data
      - ./neo4j/import:/import
    healthcheck:
      test: ["CMD", "cypher-shell", "-u", "neo4j", "-p", "password", "MATCH (n) RETURN count(n);"]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - tabular-neo4j-network

networks:
  tabular-neo4j-network:
    driver: bridge
